/**
 * @file RepccData.hpp
 * @brief Modeling data for the REPCC model.
 *
 * Generated by GridKit/Model/PhasorDynamics/data/models.py
 */

#pragma once

#include <cstddef>

#include <GridKit/Model/PhasorDynamics/ComponentData.hpp>

namespace GridKit
{
  namespace PhasorDynamics
  {
    namespace Controller
    {
      /// Parameter keys for the REPCC model.
      enum class RepccParameters
      {
        tfltr,      ///< \f$T_{\mathrm{fltr}}\f$ Measurement transducer time constant [s]
        kp,         ///< \f$K_{\mathrm{p}}\f$ Proportional gain of reactive power controller [pu]
        ki,         ///< \f$K_{\mathrm{i}}\f$ Integral gain of reactive power controller [pu]
        tft,        ///< \f$T_{\mathrm{ft}}\f$ Lead time constant [s]
        tfv,        ///< \f$T_{\mathrm{fv}}\f$ Lag time constant [s]
        refflg,     ///< \f$R_{\mathrm{efflg}}\f$ 0 reactive power control, 1 voltage control, 2 power factor control (REPC_C only)
        vfrz,       ///< \f$V_{\mathrm{frz}}\f$ Voltage below which controller states are frozen [pu]
        tfrz,       ///< \f$T_{\mathrm{frz}}\f$ Time delay during which states are kept frozen after voltage recovers above vfrz [s]
        rc,         ///< \f$R_{\mathrm{c}}\f$ Current compensation resistance [pu]
        xc,         ///< \f$X_{\mathrm{c}}\f$ Current compensation reactance [pu]
        kc,         ///< \f$K_{\mathrm{c}}\f$ Reactive droop gain [pu/pu]
        tc,         ///< \f$T_{\mathrm{c}}\f$ Time constant for reactive power measurement/filtering in the reactive droop function [s]
        vcmpflg,    ///< \f$V_{\mathrm{cmpflg}}\f$ Flag: 0 reactive droop, 1 current compensation
        emax,       ///< \f$E_{\mathrm{max}}\f$ Maximum error limit [pu]
        emin,       ///< \f$E_{\mathrm{min}}\f$ Minimum error limit [pu]
        dbd,        ///< \f$D_{\mathrm{bd}}\f$ Deadband [pu]
        qvmax,      ///< \f$Q_{\mathrm{vmax}}\f$ Maximum limit of the reactive power (or voltage) for the PI controller [pu]
        qvmin,      ///< \f$Q_{\mathrm{vmin}}\f$ Minimum limit of the reactive power (or voltage) for the PI controller [pu]
        kpg,        ///< \f$K_{\mathrm{pg}}\f$ Proportional gain for active power control [pu/pu]
        kig,        ///< \f$K_{\mathrm{ig}}\f$ Integral gain for active power control [pu/pu/s]
        tp,         ///< \f$T_{\mathrm{p}}\f$ Lag time constant on electric power measurement [s]
        fdbd1,      ///< \f$F_{\mathrm{dbd1}}\f$ Deadband for primary frequency response for overfrequency events [pu]
        fdbd2,      ///< \f$F_{\mathrm{dbd2}}\f$ Deadband for primary frequency response for underfrequency events [pu]
        femax,      ///< \f$F_{\mathrm{emax}}\f$ Maximum frequency error limit [pu]
        femin,      ///< \f$F_{\mathrm{emin}}\f$ Minimum frequency error limit [pu]
        pimax,      ///< \f$P_{\mathrm{imax}}\f$ Maximum limit of the active power PI controller [pu]
        pimin,      ///< \f$P_{\mathrm{imin}}\f$ Minimum limit of the active power PI controller [pu]
        pmax,       ///< \f$P_{\mathrm{max}}\f$ Maximum active power limit [pu]
        pmin,       ///< \f$P_{\mathrm{min}}\f$ Minimum active power limit [pu]
        prmax,      ///< \f$P_{\mathrm{rmax}}\f$ Maximum rate of increase of Pref [pu/s]
        prmin,      ///< \f$P_{\mathrm{rmin}}\f$ Maximum rate of decrease of Pref [pu/s]
        dprmax,     ///< \f$D_{\mathrm{prmax}}\f$ Maximum rate of increase of plant Pref [pu/s]
        dprmin,     ///< \f$D_{\mathrm{prmin}}\f$ Maximum rate of decrease of plant Pref [pu/s]
        tlag,       ///< \f$T_{\mathrm{lag}}\f$ Lag time constant [s]
        ddn,        ///< \f$D_{\mathrm{dn}}\f$ Downside droop for PFR (overfrequency event, pushes power down) [pu/pu]
        dup,        ///< \f$D_{\mathrm{up}}\f$ Upside droop for PFR (underfrequency event, pushes power up) [pu/pu]
        frqflg,     ///< \f$F_{\mathrm{rqflg}}\f$ Flag: 1 turns on PFR functionality, 0 turns it off
        vrefmax,    ///< \f$V_{\mathrm{refmax}}\f$ Maximum limit on Vref [pu]
        vrefmin,    ///< \f$V_{\mathrm{refmin}}\f$ Minimum limit on Vref [pu]
        qrefmax,    ///< \f$Q_{\mathrm{refmax}}\f$ Maximum limit on Qref [pu]
        qrefmin,    ///< \f$Q_{\mathrm{refmin}}\f$ Minimum limit on Qref [pu]
        dqrefmax,   ///< \f$D_{\mathrm{qrefmax}}\f$ Maximum rate of increase of Q reference [pu/s]
        dqrefmin,   ///< \f$D_{\mathrm{qrefmin}}\f$ Maximum rate of decrease of Q reference [pu/s]
        qvrmax,     ///< \f$Q_{\mathrm{vrmax}}\f$ Maximum rate of increase of Qext [pu/s]
        qvrmin,     ///< \f$Q_{\mathrm{vrmin}}\f$ Maximum rate of decrease of Qext [pu/s]
        pfmax,      ///< \f$P_{\mathrm{fmax}}\f$ Maximum limit on power factor
        pfmin,      ///< \f$P_{\mathrm{fmin}}\f$ Minimum limit on power factor
        MSSflag,    ///< \f$M_{\mathrm{SSflag}}\f$ If 1 the mechanically switched shunt switching logic is activated
        MSSbus1,    ///< \f$M_{\mathrm{SSbus1}}\f$ Bus defining the branch where Qbranch2 is measured for MSS switching [bus no.]
        MSSbus2,    ///< \f$M_{\mathrm{SSbus2}}\f$ Bus defining the branch where Qbranch2 is measured for MSS switching [bus no.]
        Qdn1,       ///< \f$Q_{\mathrm{dn1}}\f$ First stage of capacitor (reactor) switching out (in) [pu]
        Qdn2,       ///< \f$Q_{\mathrm{dn2}}\f$ Second stage of capacitor (reactor) switching out (in) [pu]
        Qup1,       ///< \f$Q_{\mathrm{up1}}\f$ First stage of capacitor (reactor) switching in (out) [pu]
        Qup2,       ///< \f$Q_{\mathrm{up2}}\f$ Second stage of capacitor (reactor) switching in (out) [pu]
        Tdelay1,    ///< \f$T_{\mathrm{delay1}}\f$ Time delay for first-stage shunt switching [s]
        Tdelay2,    ///< \f$T_{\mathrm{delay2}}\f$ Time delay for second-stage shunt switching; typically shorter than Tdelay1 [s]
        Tmssbrk,    ///< \f$T_{\mathrm{mssbrk}}\f$ Time to switch a mechanically switched shunt in or out; the breaker delay [s]
        Tout,       ///< \f$T_{\mathrm{out}}\f$ Discharging time of a capacitor just switched out, before it can be switched back in [s]
        tfrq,       ///< \f$T_{\mathrm{frq}}\f$ Frequency transducer/filter time constant [s]
        Ffwrd_flag, ///< \f$F_{\mathrm{fwrdflag}}\f$ Enable (1) or disable (0) the feedforward path
        Pefd_flag,  ///< \f$P_{\mathrm{efdflag}}\f$ Enable (1) or disable (0) electrical power feedback
        vfreq,      ///< \f$V_{\mathrm{freq}}\f$ If voltage at the frequency-monitored bus is below vfreq, measured frequency is set to 1 pu [pu]
        QVflg,      ///< \f$Q_{\mathrm{Vflg}}\f$ Flag: 0 disables volt/var control completely, 1 enables it
        dfmax,      ///< \f$D_{\mathrm{fmax}}\f$ Maximum limit on frequency deviation [pu]
        dfmin,      ///< \f$D_{\mathrm{fmin}}\f$ Minimum limit on frequency deviation [pu]
        fbus,       ///< \f$F_{\mathrm{bus}}\f$ Bus at which frequency is monitored; if zero the from-bus of the monitored branch is used [bus no.]
        FromBus,    ///< \f$F_{\mathrm{romBus}}\f$ From-bus of the monitored branch at the point of measurement [bus no.]
        ToBus,      ///< \f$T_{\mathrm{oBus}}\f$ To-bus of the monitored branch at the point of measurement [bus no.]
        BranchID,   ///< \f$B_{\mathrm{ranchID}}\f$ ID of the monitored branch at the point of measurement [ID]
      };

      /// Bus keys for the REPCC model; deferred until port integration.
      enum class RepccBuses : size_t
      {
        SIZE
      };

      /// Signal input keys for the REPCC model; deferred until port integration.
      enum class RepccSignalInputs : size_t
      {
        SIZE
      };

      /// Signal output keys for the REPCC model; deferred until port integration.
      enum class RepccSignalOutputs : size_t
      {
        SIZE
      };

      /// Monitorable variables for the REPCC model; deferred until implementation.
      enum class RepccMonitorableVariables
      {
        NONE
      };

      /**
       * @brief Model data for REPCC.
       *
       * @tparam real_type Real parameter value type.
       * @tparam index_type Integer index type.
       */
      template <typename real_type, typename index_type>
      struct RepccData : public ComponentData<real_type,
                                              index_type,
                                              RepccParameters,
                                              RepccBuses,
                                              RepccSignalInputs,
                                              RepccSignalOutputs,
                                              RepccMonitorableVariables>
      {
        RepccData() = default;

        using Parameters           = RepccParameters;
        using Buses                = RepccBuses;
        using SignalInputs         = RepccSignalInputs;
        using SignalOutputs        = RepccSignalOutputs;
        using MonitorableVariables = RepccMonitorableVariables;
      };
    } // namespace Controller
  } // namespace PhasorDynamics
} // namespace GridKit
