/**
 * @file RegccData.hpp
 * @brief Modeling data for the REGCC model.
 *
 * Generated by GridKit/Model/PhasorDynamics/data/models.py
 */

#pragma once

#include <cstddef>

#include <GridKit/Model/PhasorDynamics/ComponentData.hpp>

namespace GridKit
{
  namespace PhasorDynamics
  {
    namespace Converter
    {
      /// Parameter keys for the REGCC model.
      enum class RegccParameters
      {
        rrpwr,   ///< \f$R_{\mathrm{rpwr}}\f$ Rate of increase of active current after fault clearing [pu/s]
        tg,      ///< \f$T_{\mathrm{g}}\f$ Converter controls delay emulation time-constant [s]
        tfltr,   ///< \f$T_{\mathrm{fltr}}\f$ Voltage measurement transducer filter time-constant [s]
        iqrmax,  ///< \f$I_{\mathrm{qrmax}}\f$ Upward rate limit on reactive current command [pu/s]
        iqrmin,  ///< \f$I_{\mathrm{qrmin}}\f$ Downward rate limit on reactive current command [pu/s]
        xe,      ///< \f$X_{\mathrm{e}}\f$ Source reactance [pu]
        re,      ///< \f$R_{\mathrm{e}}\f$ Source resistance [pu]
        te,      ///< \f$T_{\mathrm{e}}\f$ Converter firing delay emulation time-constant [s]
        rateflg, ///< \f$R_{\mathrm{ateflg}}\f$ Rate limit flag: 0 means rrpwr is an active current rate limit, 1 means rrpwr is an active power rate limit
        dqflag,  ///< \f$D_{\mathrm{qflag}}\f$ P/Q priority flag: 0 means Q priority, 1 means P priority
        imax,    ///< \f$I_{\mathrm{max}}\f$ Maximum continuous converter current rating [pu]
        kip,     ///< \f$K_{\mathrm{ip}}\f$ Proportional gain of the inner-current control loops [pu/pu]
        kii,     ///< \f$K_{\mathrm{ii}}\f$ Integral gain of the inner-current control loops [pu/pu.s-1]
        kppll,   ///< \f$K_{\mathrm{ppll}}\f$ Proportional gain of phase-locked loop [rad.s-1/pu]
        kipll,   ///< \f$K_{\mathrm{ipll}}\f$ Integral gain of the phase-locked loop [rad.s-1/pu.s-1]
        wmax,    ///< \f$W_{\mathrm{max}}\f$ Phase-locked loop maximum output [rad.s-1]
        wmin,    ///< \f$W_{\mathrm{min}}\f$ Phase-locked loop minimum output [rad.s-1]
        vdip,    ///< \f$V_{\mathrm{dip}}\f$ When filtered voltage is below vdip, freeze the PLL state [pu]
      };

      /// Bus keys for the REGCC model; deferred until port integration.
      enum class RegccBuses : size_t
      {
        SIZE
      };

      /// Signal input keys for the REGCC model; deferred until port integration.
      enum class RegccSignalInputs : size_t
      {
        SIZE
      };

      /// Signal output keys for the REGCC model; deferred until port integration.
      enum class RegccSignalOutputs : size_t
      {
        SIZE
      };

      /// Monitorable variables for the REGCC model; deferred until implementation.
      enum class RegccMonitorableVariables
      {
        NONE
      };

      /**
       * @brief Model data for REGCC.
       *
       * @tparam real_type Real parameter value type.
       * @tparam index_type Integer index type.
       */
      template <typename real_type, typename index_type>
      struct RegccData : public ComponentData<real_type,
                                              index_type,
                                              RegccParameters,
                                              RegccBuses,
                                              RegccSignalInputs,
                                              RegccSignalOutputs,
                                              RegccMonitorableVariables>
      {
        RegccData() = default;

        using Parameters           = RegccParameters;
        using Buses                = RegccBuses;
        using SignalInputs         = RegccSignalInputs;
        using SignalOutputs        = RegccSignalOutputs;
        using MonitorableVariables = RegccMonitorableVariables;
      };
    } // namespace Converter
  } // namespace PhasorDynamics
} // namespace GridKit
