/**
 * @file Hyg3Data.hpp
 * @brief Modeling data for the HYG3 model.
 *
 * Generated by GridKit/Model/PhasorDynamics/data/models.py
 */

#pragma once

#include <cstddef>

#include <GridKit/Model/PhasorDynamics/ComponentData.hpp>

namespace GridKit
{
  namespace PhasorDynamics
  {
    namespace Governor
    {
      /// Parameter keys for the HYG3 model.
      enum class Hyg3Parameters
      {
        Trate,    ///< \f$T_{\mathrm{rate}}\f$ Turbine rating [MW]
        Pmax,     ///< \f$P_{\mathrm{max}}\f$ Maximum gate opening [pu of mwcap]
        Pmin,     ///< \f$P_{\mathrm{min}}\f$ Minimum gate opening [pu of mwcap]
        Cflag,    ///< \f$C_{\mathrm{flag}}\f$ Governor control flag, 1=PID, -1=Double Derivative
        Rgate,    ///< \f$R_{\mathrm{gate}}\f$ Steady-state droop, pu for governor output feedback
        Relec,    ///< \f$R_{\mathrm{elec}}\f$ Steady-state droop, pu, for electric power feedback
        Td,       ///< \f$T_{\mathrm{d}}\f$ Input filter time constant [s]
        Tf,       ///< \f$T_{\mathrm{f}}\f$ Filter time constant [s]
        Tp,       ///< \f$T_{\mathrm{p}}\f$ Lead time constant [s]
        Velopen,  ///< \f$V_{\mathrm{elopen}}\f$ Maximum gate opening velocity [pu/s]
        Velclose, ///< \f$V_{\mathrm{elclose}}\f$ Maximum gate closing velocity [pu/s]
        K1,       ///< \f$K_{1}\f$ Double derivative gain [pu]
        K2,       ///< \f$K_{2}\f$ Double derivative gain, pu, if Cflag = -1
        Ki,       ///< \f$K_{\mathrm{i}}\f$ Integral gain [pu]
        Kg,       ///< \f$K_{\mathrm{g}}\f$ Gate servo gain [pu]
        Tt,       ///< \f$T_{\mathrm{t}}\f$ Power feedback time constant [s]
        db1,      ///< \f$d_{\mathrm{b1}}\f$ Intentional deadband width [Hz]
        Eps,      ///< \f$E_{\mathrm{ps}}\f$ Intentional db hysteresis [Hz]
        db2,      ///< \f$d_{\mathrm{b2}}\f$ Unintentional deadband [MW]
        Tw,       ///< \f$T_{\mathrm{w}}\f$ Water inertia time constant [s]
        At,       ///< \f$A_{\mathrm{t}}\f$ Turbine gain [pu]
        Dturb,    ///< \f$D_{\mathrm{turb}}\f$ Turbine damping coefficient [pu]
        Qnl,      ///< \f$Q_{\mathrm{nl}}\f$ No-load flow at nominal head [pu]
        H0,       ///< \f$H_{0}\f$ Turbine nominal head [pu]
        Gv1,      ///< \f$G_{\mathrm{v1}}\f$ Nonlinear gain point 1 [pu gv]
        Pgv1,     ///< \f$P_{\mathrm{gv1}}\f$ Nonlinear gain point 1 [pu power]
        Gv2,      ///< \f$G_{\mathrm{v2}}\f$ Nonlinear gain point 2 [pu gv]
        Pgv2,     ///< \f$P_{\mathrm{gv2}}\f$ Nonlinear gain point 2 [pu power]
        Gv3,      ///< \f$G_{\mathrm{v3}}\f$ Nonlinear gain point 3 [pu gv]
        Pgv3,     ///< \f$P_{\mathrm{gv3}}\f$ Nonlinear gain point 3 [pu power]
        Gv4,      ///< \f$G_{\mathrm{v4}}\f$ Nonlinear gain point 4 [pu gv]
        Pgv4,     ///< \f$P_{\mathrm{gv4}}\f$ Nonlinear gain point 4 [pu power]
        Gv5,      ///< \f$G_{\mathrm{v5}}\f$ Nonlinear gain point 5 [pu gv]
        Pgv5,     ///< \f$P_{\mathrm{gv5}}\f$ Nonlinear gain point 5 [pu power]
        Gv6,      ///< \f$G_{\mathrm{v6}}\f$ Nonlinear gain point 6 [pu gv]
        Pgv6,     ///< \f$P_{\mathrm{gv6}}\f$ Nonlinear gain point 6 [pu power]
      };

      /// Bus keys for the HYG3 model; deferred until port integration.
      enum class Hyg3Buses : size_t
      {
        SIZE
      };

      /// Signal input keys for the HYG3 model; deferred until port integration.
      enum class Hyg3SignalInputs : size_t
      {
        SIZE
      };

      /// Signal output keys for the HYG3 model; deferred until port integration.
      enum class Hyg3SignalOutputs : size_t
      {
        SIZE
      };

      /// Monitorable variables for the HYG3 model; deferred until implementation.
      enum class Hyg3MonitorableVariables
      {
        NONE
      };

      /**
       * @brief Model data for HYG3.
       *
       * @tparam real_type Real parameter value type.
       * @tparam index_type Integer index type.
       */
      template <typename real_type, typename index_type>
      struct Hyg3Data : public ComponentData<real_type,
                                             index_type,
                                             Hyg3Parameters,
                                             Hyg3Buses,
                                             Hyg3SignalInputs,
                                             Hyg3SignalOutputs,
                                             Hyg3MonitorableVariables>
      {
        Hyg3Data() = default;

        using Parameters           = Hyg3Parameters;
        using Buses                = Hyg3Buses;
        using SignalInputs         = Hyg3SignalInputs;
        using SignalOutputs        = Hyg3SignalOutputs;
        using MonitorableVariables = Hyg3MonitorableVariables;
      };
    } // namespace Governor
  } // namespace PhasorDynamics
} // namespace GridKit
