/**
 * @file RegcbData.hpp
 * @brief Modeling data for the REGCB model.
 *
 * Generated by GridKit/Model/PhasorDynamics/data/models.py
 */

#pragma once

#include <cstddef>

#include <GridKit/Model/PhasorDynamics/ComponentData.hpp>

namespace GridKit
{
  namespace PhasorDynamics
  {
    namespace Converter
    {
      /// Parameter keys for the REGCB model.
      enum class RegcbParameters
      {
        rrpwr,   ///< \f$R_{\mathrm{rpwr}}\f$ Rate of increase of active current after fault clearing [pu/s]
        tg,      ///< \f$T_{\mathrm{g}}\f$ Converter controls delay emulation time-constant [s]
        tfltr,   ///< \f$T_{\mathrm{fltr}}\f$ Voltage measurement transducer filter time-constant [s]
        iqrmax,  ///< \f$I_{\mathrm{qrmax}}\f$ Upward rate limit on reactive current command [pu/s]
        iqrmin,  ///< \f$I_{\mathrm{qrmin}}\f$ Downward rate limit on reactive current command [pu/s]
        xe,      ///< \f$X_{\mathrm{e}}\f$ Source reactance [pu]
        re,      ///< \f$R_{\mathrm{e}}\f$ Source resistance [pu]
        te,      ///< \f$T_{\mathrm{e}}\f$ Converter firing delay emulation time-constant [s]
        rateflg, ///< \f$R_{\mathrm{ateflg}}\f$ Rate limit flag: 0 means rrpwr is an active current rate limit, 1 means rrpwr is an active power rate limit
        dqflag,  ///< \f$D_{\mathrm{qflag}}\f$ P/Q priority flag: 0 means Q priority, 1 means P priority
        imax,    ///< \f$I_{\mathrm{max}}\f$ Maximum continuous converter current rating [pu]
      };

      /// Bus keys for the REGCB model; deferred until port integration.
      enum class RegcbBuses : size_t
      {
        SIZE
      };

      /// Signal input keys for the REGCB model; deferred until port integration.
      enum class RegcbSignalInputs : size_t
      {
        SIZE
      };

      /// Signal output keys for the REGCB model; deferred until port integration.
      enum class RegcbSignalOutputs : size_t
      {
        SIZE
      };

      /// Monitorable variables for the REGCB model; deferred until implementation.
      enum class RegcbMonitorableVariables
      {
        NONE
      };

      /**
       * @brief Model data for REGCB.
       *
       * @tparam real_type Real parameter value type.
       * @tparam index_type Integer index type.
       */
      template <typename real_type, typename index_type>
      struct RegcbData : public ComponentData<real_type,
                                              index_type,
                                              RegcbParameters,
                                              RegcbBuses,
                                              RegcbSignalInputs,
                                              RegcbSignalOutputs,
                                              RegcbMonitorableVariables>
      {
        RegcbData() = default;

        using Parameters           = RegcbParameters;
        using Buses                = RegcbBuses;
        using SignalInputs         = RegcbSignalInputs;
        using SignalOutputs        = RegcbSignalOutputs;
        using MonitorableVariables = RegcbMonitorableVariables;
      };
    } // namespace Converter
  } // namespace PhasorDynamics
} // namespace GridKit
