/**
 * @file ReecdData.hpp
 * @brief Modeling data for the REECD model.
 *
 * Generated by GridKit/Model/PhasorDynamics/data/models.py
 */

#pragma once

#include <cstddef>

#include <GridKit/Model/PhasorDynamics/ComponentData.hpp>

namespace GridKit
{
  namespace PhasorDynamics
  {
    namespace Controller
    {
      /// Parameter keys for the REECD model.
      enum class ReecdParameters
      {
        vdip,      ///< \f$V_{\mathrm{dip}}\f$ The voltage below which voltage-dip logic is initiated; set to -1 to disable [pu]
        vup,       ///< \f$V_{\mathrm{up}}\f$ The voltage above which voltage-dip/up logic is initiated; set to 2 to disable [pu]
        trv,       ///< \f$T_{\mathrm{rv}}\f$ Voltage measurement transducer time constant [s]
        dbd1,      ///< \f$D_{\mathrm{bd1}}\f$ Lower deadband in voltage error [pu]
        dbd2,      ///< \f$D_{\mathrm{bd2}}\f$ Upper deadband in voltage error [pu]
        kqv,       ///< \f$K_{\mathrm{qv}}\f$ Reactive current injection proportional gain; active only during a voltage-dip/rise; 0 to disable [pu]
        iqh1,      ///< \f$I_{\mathrm{qh1}}\f$ Maximum limit on reactive current injection during a voltage-dip/rise [pu]
        iql1,      ///< \f$I_{\mathrm{ql1}}\f$ Minimum limit on reactive current injection during a voltage-dip/rise [pu]
        vref0,     ///< \f$V_{\mathrm{ref0}}\f$ If left as zero most commercial tools initialize it appropriately; otherwise set to 1 pu [pu]
        iqfrz,     ///< \f$I_{\mathrm{qfrz}}\f$ Reactive current held during the voltage-dip state transition; see model text [pu]
        thld,      ///< \f$T_{\mathrm{hld}}\f$ Hold time for the reactive current command after a voltage dip; sign selects the logic branch [s]
        thld2,     ///< \f$T_{\mathrm{hld2}}\f$ Hold time for the active current command after a voltage dip [s]
        tp,        ///< \f$T_{\mathrm{p}}\f$ Electrical power measurement transducer time constant [s]
        qmax,      ///< \f$Q_{\mathrm{max}}\f$ Maximum reactive output limit; set to 9999 to disable [pu]
        qmin,      ///< \f$Q_{\mathrm{min}}\f$ Minimum reactive output limit; set to -9999 to disable [pu]
        vmax,      ///< \f$V_{\mathrm{max}}\f$ Voltage control maximum limit [pu]
        vmin,      ///< \f$V_{\mathrm{min}}\f$ Voltage control minimum limit [pu]
        kqp,       ///< \f$K_{\mathrm{qp}}\f$ Proportional gain of the local Q-control PI regulator [pu/pu]
        kqi,       ///< \f$K_{\mathrm{qi}}\f$ Integral gain of the local Q-control PI regulator [pu/pu/s]
        kvp,       ///< \f$K_{\mathrm{vp}}\f$ Proportional gain of the local V-control PI regulator [pu/pu]
        kvi,       ///< \f$K_{\mathrm{vi}}\f$ Integral gain of the local V-control PI regulator [pu/pu/s]
        vref1,     ///< \f$V_{\mathrm{ref1}}\f$ Reference bias; typically zero, change only if instructed by OEM data [pu]
        tiq,       ///< \f$T_{\mathrm{iq}}\f$ Controller time-constant [s]
        dpmax,     ///< \f$D_{\mathrm{pmax}}\f$ Up ramp-rate on power reference; set to 999 to disable [pu/s]
        dpmin,     ///< \f$D_{\mathrm{pmin}}\f$ Down ramp-rate on power reference; set to -999 to disable [pu/s]
        pmax,      ///< \f$P_{\mathrm{max}}\f$ Maximum power reference [pu]
        pmin,      ///< \f$P_{\mathrm{min}}\f$ Minimum power reference; must not be negative for REEC_A, may be negative for REEC_C/D when modeling storage [pu]
        imax,      ///< \f$I_{\mathrm{max}}\f$ Maximum current limit of the device [pu]
        tpord,     ///< \f$T_{\mathrm{pord}}\f$ Time constant for power order [s]
        pfflag,    ///< \f$P_{\mathrm{fflag}}\f$ Power-factor control flag; depends on actual control strategy, obtain from OEM
        vflag,     ///< \f$V_{\mathrm{flag}}\f$ Voltage control flag; depends on actual control strategy, obtain from OEM
        qflag,     ///< \f$Q_{\mathrm{flag}}\f$ Reactive control flag; depends on actual control strategy, obtain from OEM
        pflag,     ///< \f$P_{\mathrm{flag}}\f$ Active power flag; depends on actual control strategy, obtain from OEM
        pqflag,    ///< \f$P_{\mathrm{qflag}}\f$ Current-limit priority flag: 0 means Q priority, 1 means P priority
        SOCini,    ///< \f$S_{\mathrm{OCini}}\f$ Initial state of charge of the battery [pu]
        SOCmax,    ///< \f$S_{\mathrm{OCmax}}\f$ Maximum state of charge of the battery [pu]
        SOCmin,    ///< \f$S_{\mathrm{OCmin}}\f$ Minimum state of charge of the battery [pu]
        T,         ///< \f$T\f$ Charging/discharging time constant; many thousands of seconds [s]
        vcmpflag,  ///< \f$V_{\mathrm{cmpflag}}\f$ Type of compensation: 1 current compensation, 0 reactive droop
        rc,        ///< \f$R_{\mathrm{c}}\f$ Current compensation resistance [pu]
        xc,        ///< \f$X_{\mathrm{c}}\f$ Current compensation reactance [pu]
        tr1,       ///< \f$T_{\mathrm{r1}}\f$ Filter time constant [s]
        kc,        ///< \f$K_{\mathrm{c}}\f$ Reactive droop gain [pu/pu]
        ke,        ///< \f$K_{\mathrm{e}}\f$ Scaling on Ipmin; 0 for a generator, non-zero for a storage device [pu]
        vblkh,     ///< \f$V_{\mathrm{blkh}}\f$ Voltage above which the converter will block [pu]
        vblkl,     ///< \f$V_{\mathrm{blkl}}\f$ Voltage below which the converter will block [pu]
        tblkdelay, ///< \f$T_{\mathrm{blkdelay}}\f$ Time delay for unblocking after voltage recovers [s]
        vq1,       ///< \f$V_{\mathrm{q1}}\f$ Voltage-dependent limit table point 1 (voltage) [pu]
        vq2,       ///< \f$V_{\mathrm{q2}}\f$ Voltage-dependent limit table point 2 (voltage) [pu]
        vq3,       ///< \f$V_{\mathrm{q3}}\f$ Voltage-dependent limit table point 3 (voltage) [pu]
        vq4,       ///< \f$V_{\mathrm{q4}}\f$ Voltage-dependent limit table point 4 (voltage) [pu]
        vq5,       ///< \f$V_{\mathrm{q5}}\f$ Voltage-dependent limit table point 5 (voltage) [pu]
        vq6,       ///< \f$V_{\mathrm{q6}}\f$ Voltage-dependent limit table point 6 (voltage) [pu]
        vq7,       ///< \f$V_{\mathrm{q7}}\f$ Voltage-dependent limit table point 7 (voltage) [pu]
        vq8,       ///< \f$V_{\mathrm{q8}}\f$ Voltage-dependent limit table point 8 (voltage) [pu]
        vq9,       ///< \f$V_{\mathrm{q9}}\f$ Voltage-dependent limit table point 9 (voltage) [pu]
        vq10,      ///< \f$V_{\mathrm{q10}}\f$ Voltage-dependent limit table point 10 (voltage) [pu]
        iq1,       ///< \f$I_{\mathrm{q1}}\f$ Voltage-dependent limit table point 1 (reactive current) [pu]
        iq2,       ///< \f$I_{\mathrm{q2}}\f$ Voltage-dependent limit table point 2 (reactive current) [pu]
        iq3,       ///< \f$I_{\mathrm{q3}}\f$ Voltage-dependent limit table point 3 (reactive current) [pu]
        iq4,       ///< \f$I_{\mathrm{q4}}\f$ Voltage-dependent limit table point 4 (reactive current) [pu]
        iq5,       ///< \f$I_{\mathrm{q5}}\f$ Voltage-dependent limit table point 5 (reactive current) [pu]
        iq6,       ///< \f$I_{\mathrm{q6}}\f$ Voltage-dependent limit table point 6 (reactive current) [pu]
        iq7,       ///< \f$I_{\mathrm{q7}}\f$ Voltage-dependent limit table point 7 (reactive current) [pu]
        iq8,       ///< \f$I_{\mathrm{q8}}\f$ Voltage-dependent limit table point 8 (reactive current) [pu]
        iq9,       ///< \f$I_{\mathrm{q9}}\f$ Voltage-dependent limit table point 9 (reactive current) [pu]
        iq10,      ///< \f$I_{\mathrm{q10}}\f$ Voltage-dependent limit table point 10 (reactive current) [pu]
        vp1,       ///< \f$V_{\mathrm{p1}}\f$ Voltage-dependent limit table point 1 (voltage) [pu]
        vp2,       ///< \f$V_{\mathrm{p2}}\f$ Voltage-dependent limit table point 2 (voltage) [pu]
        vp3,       ///< \f$V_{\mathrm{p3}}\f$ Voltage-dependent limit table point 3 (voltage) [pu]
        vp4,       ///< \f$V_{\mathrm{p4}}\f$ Voltage-dependent limit table point 4 (voltage) [pu]
        vp5,       ///< \f$V_{\mathrm{p5}}\f$ Voltage-dependent limit table point 5 (voltage) [pu]
        vp6,       ///< \f$V_{\mathrm{p6}}\f$ Voltage-dependent limit table point 6 (voltage) [pu]
        vp7,       ///< \f$V_{\mathrm{p7}}\f$ Voltage-dependent limit table point 7 (voltage) [pu]
        vp8,       ///< \f$V_{\mathrm{p8}}\f$ Voltage-dependent limit table point 8 (voltage) [pu]
        vp9,       ///< \f$V_{\mathrm{p9}}\f$ Voltage-dependent limit table point 9 (voltage) [pu]
        vp10,      ///< \f$V_{\mathrm{p10}}\f$ Voltage-dependent limit table point 10 (voltage) [pu]
        ip1,       ///< \f$I_{\mathrm{p1}}\f$ Voltage-dependent limit table point 1 (active current) [pu]
        ip2,       ///< \f$I_{\mathrm{p2}}\f$ Voltage-dependent limit table point 2 (active current) [pu]
        ip3,       ///< \f$I_{\mathrm{p3}}\f$ Voltage-dependent limit table point 3 (active current) [pu]
        ip4,       ///< \f$I_{\mathrm{p4}}\f$ Voltage-dependent limit table point 4 (active current) [pu]
        ip5,       ///< \f$I_{\mathrm{p5}}\f$ Voltage-dependent limit table point 5 (active current) [pu]
        ip6,       ///< \f$I_{\mathrm{p6}}\f$ Voltage-dependent limit table point 6 (active current) [pu]
        ip7,       ///< \f$I_{\mathrm{p7}}\f$ Voltage-dependent limit table point 7 (active current) [pu]
        ip8,       ///< \f$I_{\mathrm{p8}}\f$ Voltage-dependent limit table point 8 (active current) [pu]
        ip9,       ///< \f$I_{\mathrm{p9}}\f$ Voltage-dependent limit table point 9 (active current) [pu]
        ip10,      ///< \f$I_{\mathrm{p10}}\f$ Voltage-dependent limit table point 10 (active current) [pu]
      };

      /// Bus keys for the REECD model; deferred until port integration.
      enum class ReecdBuses : size_t
      {
        SIZE
      };

      /// Signal input keys for the REECD model; deferred until port integration.
      enum class ReecdSignalInputs : size_t
      {
        SIZE
      };

      /// Signal output keys for the REECD model; deferred until port integration.
      enum class ReecdSignalOutputs : size_t
      {
        SIZE
      };

      /// Monitorable variables for the REECD model; deferred until implementation.
      enum class ReecdMonitorableVariables
      {
        NONE
      };

      /**
       * @brief Model data for REECD.
       *
       * @tparam real_type Real parameter value type.
       * @tparam index_type Integer index type.
       */
      template <typename real_type, typename index_type>
      struct ReecdData : public ComponentData<real_type,
                                              index_type,
                                              ReecdParameters,
                                              ReecdBuses,
                                              ReecdSignalInputs,
                                              ReecdSignalOutputs,
                                              ReecdMonitorableVariables>
      {
        ReecdData() = default;

        using Parameters           = ReecdParameters;
        using Buses                = ReecdBuses;
        using SignalInputs         = ReecdSignalInputs;
        using SignalOutputs        = ReecdSignalOutputs;
        using MonitorableVariables = ReecdMonitorableVariables;
      };
    } // namespace Controller
  } // namespace PhasorDynamics
} // namespace GridKit
