/**
 * @file Regfmc1Data.hpp
 * @brief Modeling data for the REGFMC1 model.
 *
 * Generated by GridKit/Model/PhasorDynamics/data/models.py
 */

#pragma once

#include <cstddef>

#include <GridKit/Model/PhasorDynamics/ComponentData.hpp>

namespace GridKit
{
  namespace PhasorDynamics
  {
    namespace Converter
    {
      /// Parameter keys for the REGFMC1 model.
      enum class Regfmc1Parameters
      {
        FFlag,        ///< \f$F_{\mathrm{Flag}}\f$ A flag to determine whether the power-frequency droop is enabled (1) or disabled (0)
        PQFlag,       ///< \f$P_{\mathrm{QFlag}}\f$ A flag to determine whether P priority (1) or Q priority (0) is selected
        Rs,           ///< \f$R_{\mathrm{s}}\f$ Virtual resistance (0 pu <= Rs <= Xs/4) [pu]
        Xs,           ///< \f$X_{\mathrm{s}}\f$ Virtual reactance (0.04 pu <= Xs <= 0.4 pu) [pu]
        mq,           ///< \f$m_{\mathrm{q}}\f$ Q-V droop gain of the GFM branch [pu]
        kq,           ///< \f$k_{\mathrm{q}}\f$ A binary value that is either 0 or 1
        kpE,          ///< \f$k_{\mathrm{pE}}\f$ Proportional gain of the voltage PI loop of the GFM branch [pu]
        kiE,          ///< \f$k_{\mathrm{iE}}\f$ Integral gain of the voltage PI loop of the GFM branch [pu/s]
        dEmax,        ///< \f$\Delta E_{\mathrm{max}}\f$ Upper limit of the voltage PI loop of the GFM branch [pu]
        dEmin,        ///< \f$\Delta E_{\mathrm{min}}\f$ Lower limit of the voltage PI loop of the GFM branch [pu]
        Vrefmax,      ///< \f$V_{\mathrm{refmax}}\f$ Upper limit of the voltage reference of the GFM branch [pu]
        Vrefmin,      ///< \f$V_{\mathrm{refmin}}\f$ Lower limit of the voltage reference of the GFM branch [pu]
        TVref,        ///< \f$T_{\mathrm{Vref}}\f$ Time constant of low-pass filter of the GFM branch (voltage reference) [s]
        TVSM,         ///< \f$T_{\mathrm{VSM}}\f$ Time constant of low-pass filter of the GFM branch (internal voltage) [s]
        TVf,          ///< \f$T_{\mathrm{Vf}}\f$ Time constant of low-pass filter of the GFM branch (voltage measurement) [s]
        TIf,          ///< \f$T_{\mathrm{If}}\f$ Time constant of low-pass filter of the GFM branch (current measurement) [s]
        H,            ///< \f$H\f$ Inertia time constant of the GFM branch [s]
        D1,           ///< \f$D_{1}\f$ Damping of the GFM branch [pu]
        D2,           ///< \f$D_{2}\f$ Transient damping of the GFM branch [pu]
        wD,           ///< \f$\omega_{\mathrm{D}}\f$ Angular frequency of the washout block of the GFM branch [pu]
        mp,           ///< \f$m_{\mathrm{p}}\f$ P-f droop gain of the GFM branch [pu]
        dwmax,        ///< \f$\Delta\omega_{\mathrm{max}}\f$ Upper limit of the VSM integrator of the GFM branch [pu]
        dwmin,        ///< \f$\Delta\omega_{\mathrm{min}}\f$ Lower limit of the VSM integrator of the GFM branch [pu]
        wrefmax,      ///< \f$\omega_{\mathrm{refmax}}\f$ Upper limit of the frequency reference of the GFM branch [pu]
        wrefmin,      ///< \f$\omega_{\mathrm{refmin}}\f$ Lower limit of the frequency reference of the GFM branch [pu]
        Twr,          ///< \f$T_{\mathrm{wr}}\f$ Time constant of low-pass filter of the GFM branch (frequency reference) [s]
        Twm,          ///< \f$T_{\mathrm{wm}}\f$ Time constant of low-pass filter of the GFM branch (measured frequency) [s]
        TPf,          ///< \f$T_{\mathrm{Pf}}\f$ Time constant of low-pass filter of the GFM branch (active power) [s]
        Pcmd_GFL_max, ///< \f$P_{\mathrm{cmdGFLmax}}\f$ Upper limit of the active power reference for the GFL branch [pu]
        Pcmd_GFL_min, ///< \f$P_{\mathrm{cmdGFLmin}}\f$ Lower limit of the active power reference for the GFL branch [pu]
        Qcmd_GFL_max, ///< \f$Q_{\mathrm{cmdGFLmax}}\f$ Upper limit of the reactive power reference for the GFL branch [pu]
        Qcmd_GFL_min, ///< \f$Q_{\mathrm{cmdGFLmin}}\f$ Lower limit of the reactive power reference for the GFL branch [pu]
        Vmin,         ///< \f$V_{\mathrm{min}}\f$ Lower voltage limit of the GFL branch [pu]
        Vref0,        ///< \f$V_{\mathrm{ref0}}\f$ Voltage reference of the GFL branch [pu]
        kqv,          ///< \f$k_{\mathrm{qv}}\f$ Voltage control factor of the GFL branch [pu]
        dbVL1,        ///< \f$d_{\mathrm{bVL1}}\f$ Lower threshold of the deadband of the GFL branch [pu]
        dbVH1,        ///< \f$d_{\mathrm{bVH1}}\f$ Upper threshold of the deadband of the GFL branch [pu]
        kf,           ///< \f$k_{\mathrm{f}}\f$ Factor determining Iqmax (PQFlag=0) or Idmax (PQFlag=1) of the GFL branch; if 0 the software resets it to 1 with a warning [pu]
        Imax,         ///< \f$I_{\mathrm{max}}\f$ Maximum output current [pu]
        w0,           ///< \f$\omega_{0}\f$ Rated angular frequency; usually set in the solution environment rather than as a model input [rad/s]
      };

      /// Bus keys for the REGFMC1 model; deferred until port integration.
      enum class Regfmc1Buses : size_t
      {
        SIZE
      };

      /// Signal input keys for the REGFMC1 model; deferred until port integration.
      enum class Regfmc1SignalInputs : size_t
      {
        SIZE
      };

      /// Signal output keys for the REGFMC1 model; deferred until port integration.
      enum class Regfmc1SignalOutputs : size_t
      {
        SIZE
      };

      /// Monitorable variables for the REGFMC1 model; deferred until implementation.
      enum class Regfmc1MonitorableVariables
      {
        NONE
      };

      /**
       * @brief Model data for REGFMC1.
       *
       * @tparam real_type Real parameter value type.
       * @tparam index_type Integer index type.
       */
      template <typename real_type, typename index_type>
      struct Regfmc1Data : public ComponentData<real_type,
                                                index_type,
                                                Regfmc1Parameters,
                                                Regfmc1Buses,
                                                Regfmc1SignalInputs,
                                                Regfmc1SignalOutputs,
                                                Regfmc1MonitorableVariables>
      {
        Regfmc1Data() = default;

        using Parameters           = Regfmc1Parameters;
        using Buses                = Regfmc1Buses;
        using SignalInputs         = Regfmc1SignalInputs;
        using SignalOutputs        = Regfmc1SignalOutputs;
        using MonitorableVariables = Regfmc1MonitorableVariables;
      };
    } // namespace Converter
  } // namespace PhasorDynamics
} // namespace GridKit
