/**
 * @file RegcaData.hpp
 * @brief Modeling data for the REGCA model.
 *
 * Generated by GridKit/Model/PhasorDynamics/data/models.py
 */

#pragma once

#include <cstddef>

#include <GridKit/Model/PhasorDynamics/ComponentData.hpp>

namespace GridKit
{
  namespace PhasorDynamics
  {
    namespace Converter
    {
      /// Parameter keys for the REGCA model.
      enum class RegcaParameters
      {
        lvplsw, ///< \f$L_{\mathrm{vplsw}}\f$ A flag set according to OEM instructions to turn on (1) or off (0) the LVPL curve
        brkpt,  ///< \f$B_{\mathrm{rkpt}}\f$ Used only when Lvplsw = 1; voltage point below which active current is linearly reduced as a function of voltage until it reaches zero at zerox [pu]
        zerox,  ///< \f$Z_{\mathrm{erox}}\f$ Used only when Lvplsw = 1; voltage point below which active current become zero [pu]
        lvpl1,  ///< \f$L_{\mathrm{vpl1}}\f$ Active current limit at Brkpt voltage and above [pu]
        vtmax,  ///< \f$V_{\mathrm{tmax}}\f$ Network-interface numerical-stability parameter (see High Voltage Reactive Current Management logic) [pu]
        lvpnt1, ///< \f$L_{\mathrm{vpnt1}}\f$ Network-interface numerical-stability parameter [pu]
        lvpnt0, ///< \f$L_{\mathrm{vpnt0}}\f$ Network-interface numerical-stability parameter [pu]
        qmin,   ///< \f$Q_{\mathrm{min}}\f$ Network-interface numerical-stability parameter; not the minimum reactive power of the device [pu]
        accel,  ///< \f$A_{\mathrm{ccel}}\f$ Acceleration factor for the numerical solution of the network interface to help with network convergence
        rrpwr,  ///< \f$R_{\mathrm{rpwr}}\f$ Rate of increase of active current after fault clearing [pu/s]
        tg,     ///< \f$T_{\mathrm{g}}\f$ Converter controls delay emulation time-constant [s]
        tfltr,  ///< \f$T_{\mathrm{fltr}}\f$ Voltage measurement transducer filter time-constant [s]
        iqrmax, ///< \f$I_{\mathrm{qrmax}}\f$ Upward rate limit on reactive current command [pu/s]
        iqrmin, ///< \f$I_{\mathrm{qrmin}}\f$ Downward rate limit on reactive current command [pu/s]
        xe,     ///< \f$X_{\mathrm{e}}\f$ Source reactance [pu]
      };

      /// Bus keys for the REGCA model; deferred until port integration.
      enum class RegcaBuses : size_t
      {
        SIZE
      };

      /// Signal input keys for the REGCA model; deferred until port integration.
      enum class RegcaSignalInputs : size_t
      {
        SIZE
      };

      /// Signal output keys for the REGCA model; deferred until port integration.
      enum class RegcaSignalOutputs : size_t
      {
        SIZE
      };

      /// Monitorable variables for the REGCA model; deferred until implementation.
      enum class RegcaMonitorableVariables
      {
        NONE
      };

      /**
       * @brief Model data for REGCA.
       *
       * @tparam real_type Real parameter value type.
       * @tparam index_type Integer index type.
       */
      template <typename real_type, typename index_type>
      struct RegcaData : public ComponentData<real_type,
                                              index_type,
                                              RegcaParameters,
                                              RegcaBuses,
                                              RegcaSignalInputs,
                                              RegcaSignalOutputs,
                                              RegcaMonitorableVariables>
      {
        RegcaData() = default;

        using Parameters           = RegcaParameters;
        using Buses                = RegcaBuses;
        using SignalInputs         = RegcaSignalInputs;
        using SignalOutputs        = RegcaSignalOutputs;
        using MonitorableVariables = RegcaMonitorableVariables;
      };
    } // namespace Converter
  } // namespace PhasorDynamics
} // namespace GridKit
