/**
 * @file HygovdData.hpp
 * @brief Modeling data for the HYGOVD model.
 *
 * Generated by GridKit/Model/PhasorDynamics/data/models.py
 */

#pragma once

#include <cstddef>

#include <GridKit/Model/PhasorDynamics/ComponentData.hpp>

namespace GridKit
{
  namespace PhasorDynamics
  {
    namespace Governor
    {
      /// Parameter keys for the HYGOVD model.
      enum class HygovdParameters
      {
        Rperm, ///< \f$R_{\mathrm{perm}}\f$ Permanent droop [pu]
        Rtemp, ///< \f$R_{\mathrm{temp}}\f$ Temporary droop [pu]
        Tr,    ///< \f$T_{\mathrm{r}}\f$ Washout time constant [s]
        Tf,    ///< \f$T_{\mathrm{f}}\f$ Filter time constant [s]
        Tg,    ///< \f$T_{\mathrm{g}}\f$ Gate servo time constant [s]
        Velm,  ///< \f$V_{\mathrm{elm}}\f$ Maximum gate velocity [pu/s]
        Gmax,  ///< \f$G_{\mathrm{max}}\f$ Maximum gate velocity [pu of mwcap]
        Gmin,  ///< \f$G_{\mathrm{min}}\f$ Minimum gate velocity [pu of mwcap]
        Tw,    ///< \f$T_{\mathrm{w}}\f$ Water inertia time constant [s]
        At,    ///< \f$A_{\mathrm{t}}\f$ Turbine gain [pu]
        Dturb, ///< \f$D_{\mathrm{turb}}\f$ Turbine damping coefficient [pu]
        Qnl,   ///< \f$Q_{\mathrm{nl}}\f$ No-load flow at nominal head [pu]
        dbH,   ///< \f$d_{\mathrm{bH}}\f$ Deadband High [pu]
        dbL,   ///< \f$d_{\mathrm{bL}}\f$ Deadband Low [pu]
        Trate, ///< \f$T_{\mathrm{rate}}\f$ Turbine rating [MW]
      };

      /// Bus keys for the HYGOVD model; deferred until port integration.
      enum class HygovdBuses : size_t
      {
        SIZE
      };

      /// Signal input keys for the HYGOVD model; deferred until port integration.
      enum class HygovdSignalInputs : size_t
      {
        SIZE
      };

      /// Signal output keys for the HYGOVD model; deferred until port integration.
      enum class HygovdSignalOutputs : size_t
      {
        SIZE
      };

      /// Monitorable variables for the HYGOVD model; deferred until implementation.
      enum class HygovdMonitorableVariables
      {
        NONE
      };

      /**
       * @brief Model data for HYGOVD.
       *
       * @tparam real_type Real parameter value type.
       * @tparam index_type Integer index type.
       */
      template <typename real_type, typename index_type>
      struct HygovdData : public ComponentData<real_type,
                                               index_type,
                                               HygovdParameters,
                                               HygovdBuses,
                                               HygovdSignalInputs,
                                               HygovdSignalOutputs,
                                               HygovdMonitorableVariables>
      {
        HygovdData() = default;

        using Parameters           = HygovdParameters;
        using Buses                = HygovdBuses;
        using SignalInputs         = HygovdSignalInputs;
        using SignalOutputs        = HygovdSignalOutputs;
        using MonitorableVariables = HygovdMonitorableVariables;
      };
    } // namespace Governor
  } // namespace PhasorDynamics
} // namespace GridKit
