/**
 * @file Ieeeg1dData.hpp
 * @brief Modeling data for the IEEEG1D model.
 *
 * Generated by GridKit/Model/PhasorDynamics/data/models.py
 */

#pragma once

#include <cstddef>

#include <GridKit/Model/PhasorDynamics/ComponentData.hpp>

namespace GridKit
{
  namespace PhasorDynamics
  {
    namespace Governor
    {
      /// Parameter keys for the IEEEG1D model.
      enum class Ieeeg1dParameters
      {
        K,     ///< \f$K\f$ Governor gain (recirpocal of droop) [pu]
        T1,    ///< \f$T_{1}\f$ Governor lag time constant [s]
        T2,    ///< \f$T_{2}\f$ governor lead time constant [s]
        T3,    ///< \f$T_{3}\f$ Valve positioner time constant [s]
        Uo,    ///< \f$U_{\mathrm{o}}\f$ Maximum valve opening velocity [pu/s]
        Uc,    ///< \f$U_{\mathrm{c}}\f$ Maximum valve closing velocity [pu/s]
        Pmax,  ///< \f$P_{\mathrm{max}}\f$ Maximum valve opening [pu of mwcap]
        Pmin,  ///< \f$P_{\mathrm{min}}\f$ Minimum valve opening [pu of mwcap]
        T4,    ///< \f$T_{4}\f$ High pressure turbine bowl time constant [s]
        K1,    ///< \f$K_{1}\f$ Fraction of hp shaft power after first boiler pass
        K2,    ///< \f$K_{2}\f$ Fraction of lp shaft power after first boiler pass
        T5,    ///< \f$T_{5}\f$ Reheater time constant [s]
        K3,    ///< \f$K_{3}\f$ Fraction of hp shaft power after second boiler pass
        K4,    ///< \f$K_{4}\f$ Fraction of lp shaft power after second boiler pass
        T6,    ///< \f$T_{6}\f$ Crossover time constant [s]
        K5,    ///< \f$K_{5}\f$ Fraction of hp shaft power after third boiler pass
        K6,    ///< \f$K_{6}\f$ Fraction of lp shaft power after third boiler pass
        T7,    ///< \f$T_{7}\f$ Double reheat time constant [s]
        K7,    ///< \f$K_{7}\f$ Fraction of hp shaft power after fourth boiler pass
        K8,    ///< \f$K_{8}\f$ Fraction of lp shaft power after fourth boiler pass
        dbH,   ///< \f$d_{\mathrm{bH}}\f$ Deadband High [pu]
        dbL,   ///< \f$d_{\mathrm{bL}}\f$ Deadband Low [pu]
        Trate, ///< \f$T_{\mathrm{rate}}\f$ Turbine rating [MW]
      };

      /// Bus keys for the IEEEG1D model; deferred until port integration.
      enum class Ieeeg1dBuses : size_t
      {
        SIZE
      };

      /// Signal input keys for the IEEEG1D model; deferred until port integration.
      enum class Ieeeg1dSignalInputs : size_t
      {
        SIZE
      };

      /// Signal output keys for the IEEEG1D model; deferred until port integration.
      enum class Ieeeg1dSignalOutputs : size_t
      {
        SIZE
      };

      /// Monitorable variables for the IEEEG1D model; deferred until implementation.
      enum class Ieeeg1dMonitorableVariables
      {
        NONE
      };

      /**
       * @brief Model data for IEEEG1D.
       *
       * @tparam real_type Real parameter value type.
       * @tparam index_type Integer index type.
       */
      template <typename real_type, typename index_type>
      struct Ieeeg1dData : public ComponentData<real_type,
                                                index_type,
                                                Ieeeg1dParameters,
                                                Ieeeg1dBuses,
                                                Ieeeg1dSignalInputs,
                                                Ieeeg1dSignalOutputs,
                                                Ieeeg1dMonitorableVariables>
      {
        Ieeeg1dData() = default;

        using Parameters           = Ieeeg1dParameters;
        using Buses                = Ieeeg1dBuses;
        using SignalInputs         = Ieeeg1dSignalInputs;
        using SignalOutputs        = Ieeeg1dSignalOutputs;
        using MonitorableVariables = Ieeeg1dMonitorableVariables;
      };
    } // namespace Governor
  } // namespace PhasorDynamics
} // namespace GridKit
