/**
 * @file Ieeeg1Data.hpp
 * @brief Modeling data for the IEEEG1 model.
 *
 * Generated by GridKit/Model/PhasorDynamics/data/models.py
 */

#pragma once

#include <cstddef>

#include <GridKit/Model/PhasorDynamics/ComponentData.hpp>

namespace GridKit
{
  namespace PhasorDynamics
  {
    namespace Governor
    {
      /// Parameter keys for the IEEEG1 model.
      enum class Ieeeg1Parameters
      {
        K,     ///< \f$K\f$ Governor gain (recirpocal of droop) [pu]
        T1,    ///< \f$T_{1}\f$ Governor lag time constant [s]
        T2,    ///< \f$T_{2}\f$ governor lead time constant [s]
        T3,    ///< \f$T_{3}\f$ Valve positioner time constant [s]
        Uo,    ///< \f$U_{\mathrm{o}}\f$ Maximum valve opening velocity [pu/s]
        Uc,    ///< \f$U_{\mathrm{c}}\f$ Maximum valve closing velocity [pu/s]
        Pmax,  ///< \f$P_{\mathrm{max}}\f$ Maximum valve opening [pu of mwcap]
        Pmin,  ///< \f$P_{\mathrm{min}}\f$ Minimum valve opening [pu of mwcap]
        T4,    ///< \f$T_{4}\f$ High pressure turbine bowl time constant [s]
        K1,    ///< \f$K_{1}\f$ Fraction of hp shaft power after first boiler pass
        K2,    ///< \f$K_{2}\f$ Fraction of lp shaft power after first boiler pass
        T5,    ///< \f$T_{5}\f$ Reheater time constant [s]
        K3,    ///< \f$K_{3}\f$ Fraction of hp shaft power after second boiler pass
        K4,    ///< \f$K_{4}\f$ Fraction of lp shaft power after second boiler pass
        T6,    ///< \f$T_{6}\f$ Crossover time constant [s]
        K5,    ///< \f$K_{5}\f$ Fraction of hp shaft power after third boiler pass
        K6,    ///< \f$K_{6}\f$ Fraction of lp shaft power after third boiler pass
        T7,    ///< \f$T_{7}\f$ Double reheat time constant [s]
        K7,    ///< \f$K_{7}\f$ Fraction of hp shaft power after fourth boiler pass
        K8,    ///< \f$K_{8}\f$ Fraction of lp shaft power after fourth boiler pass
        db1,   ///< \f$d_{\mathrm{b1}}\f$ Intentional deadband width [Hz]
        Eps,   ///< \f$E_{\mathrm{ps}}\f$ Intentional db hysteresis [Hz]
        db2,   ///< \f$d_{\mathrm{b2}}\f$ Unintentional deadband [MW]
        Gv1,   ///< \f$G_{\mathrm{v1}}\f$ Nonlinear gain point 1 [pu gv]
        Pgv1,  ///< \f$P_{\mathrm{gv1}}\f$ Nonlinear gain point 1 [pu power]
        Gv2,   ///< \f$G_{\mathrm{v2}}\f$ Nonlinear gain point 2 [pu gv]
        Pgv2,  ///< \f$P_{\mathrm{gv2}}\f$ Nonlinear gain point 2 [pu power]
        Gv3,   ///< \f$G_{\mathrm{v3}}\f$ Nonlinear gain point 3 [pu gv]
        Pgv3,  ///< \f$P_{\mathrm{gv3}}\f$ Nonlinear gain point 3 [pu power]
        Gv4,   ///< \f$G_{\mathrm{v4}}\f$ Nonlinear gain point 4 [pu gv]
        Pgv4,  ///< \f$P_{\mathrm{gv4}}\f$ Nonlinear gain point 4 [pu power]
        Gv5,   ///< \f$G_{\mathrm{v5}}\f$ Nonlinear gain point 5 [pu gv]
        Pgv5,  ///< \f$P_{\mathrm{gv5}}\f$ Nonlinear gain point 5 [pu power]
        Gv6,   ///< \f$G_{\mathrm{v6}}\f$ Nonlinear gain point 6 [pu gv]
        Pgv6,  ///< \f$P_{\mathrm{gv6}}\f$ Nonlinear gain point 6 [pu power]
        Trate, ///< \f$T_{\mathrm{rate}}\f$ Turbine rating [MW]
      };

      /// Bus keys for the IEEEG1 model; deferred until port integration.
      enum class Ieeeg1Buses : size_t
      {
        SIZE
      };

      /// Signal input keys for the IEEEG1 model; deferred until port integration.
      enum class Ieeeg1SignalInputs : size_t
      {
        SIZE
      };

      /// Signal output keys for the IEEEG1 model; deferred until port integration.
      enum class Ieeeg1SignalOutputs : size_t
      {
        SIZE
      };

      /// Monitorable variables for the IEEEG1 model; deferred until implementation.
      enum class Ieeeg1MonitorableVariables
      {
        NONE
      };

      /**
       * @brief Model data for IEEEG1.
       *
       * @tparam real_type Real parameter value type.
       * @tparam index_type Integer index type.
       */
      template <typename real_type, typename index_type>
      struct Ieeeg1Data : public ComponentData<real_type,
                                               index_type,
                                               Ieeeg1Parameters,
                                               Ieeeg1Buses,
                                               Ieeeg1SignalInputs,
                                               Ieeeg1SignalOutputs,
                                               Ieeeg1MonitorableVariables>
      {
        Ieeeg1Data() = default;

        using Parameters           = Ieeeg1Parameters;
        using Buses                = Ieeeg1Buses;
        using SignalInputs         = Ieeeg1SignalInputs;
        using SignalOutputs        = Ieeeg1SignalOutputs;
        using MonitorableVariables = Ieeeg1MonitorableVariables;
      };
    } // namespace Governor
  } // namespace PhasorDynamics
} // namespace GridKit
