/**
 * @file RepcaData.hpp
 * @brief Modeling data for the REPCA model.
 *
 * Generated by GridKit/Model/PhasorDynamics/data/models.py
 */

#pragma once

#include <cstddef>

#include <GridKit/Model/PhasorDynamics/ComponentData.hpp>

namespace GridKit
{
  namespace PhasorDynamics
  {
    namespace Controller
    {
      /// Parameter keys for the REPCA model.
      enum class RepcaParameters
      {
        tfltr,   ///< \f$T_{\mathrm{fltr}}\f$ Measurement transducer time constant [s]
        kp,      ///< \f$K_{\mathrm{p}}\f$ Proportional gain of reactive power controller [pu]
        ki,      ///< \f$K_{\mathrm{i}}\f$ Integral gain of reactive power controller [pu]
        tft,     ///< \f$T_{\mathrm{ft}}\f$ Lead time constant [s]
        tfv,     ///< \f$T_{\mathrm{fv}}\f$ Lag time constant [s]
        refflg,  ///< \f$R_{\mathrm{efflg}}\f$ 0 reactive power control, 1 voltage control, 2 power factor control (REPC_C only)
        vfrz,    ///< \f$V_{\mathrm{frz}}\f$ Voltage below which controller states are frozen [pu]
        rc,      ///< \f$R_{\mathrm{c}}\f$ Current compensation resistance [pu]
        xc,      ///< \f$X_{\mathrm{c}}\f$ Current compensation reactance [pu]
        kc,      ///< \f$K_{\mathrm{c}}\f$ Reactive droop gain [pu/pu]
        vcmpflg, ///< \f$V_{\mathrm{cmpflg}}\f$ Flag: 0 reactive droop, 1 current compensation
        emax,    ///< \f$E_{\mathrm{max}}\f$ Maximum error limit [pu]
        emin,    ///< \f$E_{\mathrm{min}}\f$ Minimum error limit [pu]
        dbd,     ///< \f$D_{\mathrm{bd}}\f$ Deadband [pu]
        qvmax,   ///< \f$Q_{\mathrm{vmax}}\f$ Maximum limit of the reactive power (or voltage) for the PI controller [pu]
        qvmin,   ///< \f$Q_{\mathrm{vmin}}\f$ Minimum limit of the reactive power (or voltage) for the PI controller [pu]
        kpg,     ///< \f$K_{\mathrm{pg}}\f$ Proportional gain for active power control [pu/pu]
        kig,     ///< \f$K_{\mathrm{ig}}\f$ Integral gain for active power control [pu/pu/s]
        tp,      ///< \f$T_{\mathrm{p}}\f$ Lag time constant on electric power measurement [s]
        fdbd1,   ///< \f$F_{\mathrm{dbd1}}\f$ Deadband for primary frequency response for overfrequency events [pu]
        fdbd2,   ///< \f$F_{\mathrm{dbd2}}\f$ Deadband for primary frequency response for underfrequency events [pu]
        femax,   ///< \f$F_{\mathrm{emax}}\f$ Maximum frequency error limit [pu]
        femin,   ///< \f$F_{\mathrm{emin}}\f$ Minimum frequency error limit [pu]
        pimax,   ///< \f$P_{\mathrm{imax}}\f$ Maximum limit of the active power PI controller [pu]
        pimin,   ///< \f$P_{\mathrm{imin}}\f$ Minimum limit of the active power PI controller [pu]
        pmax,    ///< \f$P_{\mathrm{max}}\f$ Maximum active power limit [pu]
        pmin,    ///< \f$P_{\mathrm{min}}\f$ Minimum active power limit [pu]
        tlag,    ///< \f$T_{\mathrm{lag}}\f$ Lag time constant [s]
        ddn,     ///< \f$D_{\mathrm{dn}}\f$ Downside droop for PFR (overfrequency event, pushes power down) [pu/pu]
        dup,     ///< \f$D_{\mathrm{up}}\f$ Upside droop for PFR (underfrequency event, pushes power up) [pu/pu]
        frqflg,  ///< \f$F_{\mathrm{rqflg}}\f$ Flag: 1 turns on PFR functionality, 0 turns it off
      };

      /// Bus keys for the REPCA model; deferred until port integration.
      enum class RepcaBuses : size_t
      {
        SIZE
      };

      /// Signal input keys for the REPCA model; deferred until port integration.
      enum class RepcaSignalInputs : size_t
      {
        SIZE
      };

      /// Signal output keys for the REPCA model; deferred until port integration.
      enum class RepcaSignalOutputs : size_t
      {
        SIZE
      };

      /// Monitorable variables for the REPCA model; deferred until implementation.
      enum class RepcaMonitorableVariables
      {
        NONE
      };

      /**
       * @brief Model data for REPCA.
       *
       * @tparam real_type Real parameter value type.
       * @tparam index_type Integer index type.
       */
      template <typename real_type, typename index_type>
      struct RepcaData : public ComponentData<real_type,
                                              index_type,
                                              RepcaParameters,
                                              RepcaBuses,
                                              RepcaSignalInputs,
                                              RepcaSignalOutputs,
                                              RepcaMonitorableVariables>
      {
        RepcaData() = default;

        using Parameters           = RepcaParameters;
        using Buses                = RepcaBuses;
        using SignalInputs         = RepcaSignalInputs;
        using SignalOutputs        = RepcaSignalOutputs;
        using MonitorableVariables = RepcaMonitorableVariables;
      };
    } // namespace Controller
  } // namespace PhasorDynamics
} // namespace GridKit
