/**
 * @file HygovData.hpp
 * @brief Modeling data for the HYGOV model.
 *
 * Generated by GridKit/Model/PhasorDynamics/data/models.py
 */

#pragma once

#include <cstddef>

#include <GridKit/Model/PhasorDynamics/ComponentData.hpp>

namespace GridKit
{
  namespace PhasorDynamics
  {
    namespace Governor
    {
      /// Parameter keys for the HYGOV model.
      enum class HygovParameters
      {
        Trate,  ///< \f$T_{\mathrm{rate}}\f$ Turbine rating [MW]
        Rperm,  ///< \f$R_{\mathrm{perm}}\f$ Permanent droop [pu]
        Rtemp,  ///< \f$R_{\mathrm{temp}}\f$ Temporary droop [pu]
        Tr,     ///< \f$T_{\mathrm{r}}\f$ Washout time constant [s]
        Tf,     ///< \f$T_{\mathrm{f}}\f$ Filter time constant [s]
        Tg,     ///< \f$T_{\mathrm{g}}\f$ Gate servo time constant [s]
        Velm,   ///< \f$V_{\mathrm{elm}}\f$ Maximum gate velocity [pu/s]
        Gmax,   ///< \f$G_{\mathrm{max}}\f$ Maximum gate velocity [pu of mwcap]
        Gmin,   ///< \f$G_{\mathrm{min}}\f$ Minimum gate velocity [pu of mwcap]
        Tw,     ///< \f$T_{\mathrm{w}}\f$ Water inertia time constant [s]
        At,     ///< \f$A_{\mathrm{t}}\f$ Turbine gain [pu]
        Dturb,  ///< \f$D_{\mathrm{turb}}\f$ Turbine damping coefficient [pu]
        Qnl,    ///< \f$Q_{\mathrm{nl}}\f$ No-load flow at nominal head [pu]
        Ttur,   ///< \f$T_{\mathrm{tur}}\f$ Turbine trip flag
        Tn,     ///< \f$T_{\mathrm{n}}\f$ Lag time constant [s]
        Tnp,    ///< \f$T_{\mathrm{np}}\f$ Lead time constant [s]
        db1,    ///< \f$d_{\mathrm{b1}}\f$ Intentional deadband width [Hz]
        Eps,    ///< \f$E_{\mathrm{ps}}\f$ Intentional db hysteresis [Hz]
        db2,    ///< \f$d_{\mathrm{b2}}\f$ Unintentional deadband [MW]
        Gv0,    ///< \f$G_{\mathrm{v0}}\f$ Nonlinear gain point 0 [pu gv]
        Pgv0,   ///< \f$P_{\mathrm{gv0}}\f$ Nonlinear gain point 0 [pu power]
        Gv1,    ///< \f$G_{\mathrm{v1}}\f$ Nonlinear gain point 1 [pu gv]
        Pgv1,   ///< \f$P_{\mathrm{gv1}}\f$ Nonlinear gain point 1 [pu power]
        Gv2,    ///< \f$G_{\mathrm{v2}}\f$ Nonlinear gain point 2 [pu gv]
        Pgv2,   ///< \f$P_{\mathrm{gv2}}\f$ Nonlinear gain point 2 [pu power]
        Gv3,    ///< \f$G_{\mathrm{v3}}\f$ Nonlinear gain point 3 [pu gv]
        Pgv3,   ///< \f$P_{\mathrm{gv3}}\f$ Nonlinear gain point 3 [pu power]
        Gv4,    ///< \f$G_{\mathrm{v4}}\f$ Nonlinear gain point 4 [pu gv]
        Pgv4,   ///< \f$P_{\mathrm{gv4}}\f$ Nonlinear gain point 4 [pu power]
        Gv5,    ///< \f$G_{\mathrm{v5}}\f$ Nonlinear gain point 5 [pu gv]
        Pgv5,   ///< \f$P_{\mathrm{gv5}}\f$ Nonlinear gain point 5 [pu power]
        Hdam,   ///< \f$H_{\mathrm{dam}}\f$ Head available at dam [pu]
        Bgv0,   ///< \f$B_{\mathrm{gv0}}\f$ Kaplan blade servo point 0 [pu]
        Bgv1,   ///< \f$B_{\mathrm{gv1}}\f$ Kaplan blade servo point 1 [pu]
        Bgv2,   ///< \f$B_{\mathrm{gv2}}\f$ Kaplan blade servo point 2 [pu]
        Bgv3,   ///< \f$B_{\mathrm{gv3}}\f$ Kaplan blade servo point 3 [pu]
        Bgv4,   ///< \f$B_{\mathrm{gv4}}\f$ Kaplan blade servo point 4 [pu]
        Bgv5,   ///< \f$B_{\mathrm{gv5}}\f$ Kaplan blade servo point 5 [pu]
        Bmax,   ///< \f$B_{\mathrm{max}}\f$ Maximum blade adjustment factor
        Tblade, ///< \f$T_{\mathrm{blade}}\f$ Blade servo time constant [s]
      };

      /// Bus keys for the HYGOV model; deferred until port integration.
      enum class HygovBuses : size_t
      {
        SIZE
      };

      /// Signal input keys for the HYGOV model; deferred until port integration.
      enum class HygovSignalInputs : size_t
      {
        SIZE
      };

      /// Signal output keys for the HYGOV model; deferred until port integration.
      enum class HygovSignalOutputs : size_t
      {
        SIZE
      };

      /// Monitorable variables for the HYGOV model; deferred until implementation.
      enum class HygovMonitorableVariables
      {
        NONE
      };

      /**
       * @brief Model data for HYGOV.
       *
       * @tparam real_type Real parameter value type.
       * @tparam index_type Integer index type.
       */
      template <typename real_type, typename index_type>
      struct HygovData : public ComponentData<real_type,
                                              index_type,
                                              HygovParameters,
                                              HygovBuses,
                                              HygovSignalInputs,
                                              HygovSignalOutputs,
                                              HygovMonitorableVariables>
      {
        HygovData() = default;

        using Parameters           = HygovParameters;
        using Buses                = HygovBuses;
        using SignalInputs         = HygovSignalInputs;
        using SignalOutputs        = HygovSignalOutputs;
        using MonitorableVariables = HygovMonitorableVariables;
      };
    } // namespace Governor
  } // namespace PhasorDynamics
} // namespace GridKit
