/**
 * @file WtgtaData.hpp
 * @brief Modeling data for the WTGTA model.
 *
 * Generated by GridKit/Model/PhasorDynamics/data/models.py
 */

#pragma once

#include <cstddef>

#include <GridKit/Model/PhasorDynamics/ComponentData.hpp>

namespace GridKit
{
  namespace PhasorDynamics
  {
    namespace Wind
    {
      /// Parameter keys for the WTGTA model.
      enum class WtgtaParameters
      {
        ht,     ///< \f$H_{\mathrm{t}}\f$ Turbine inertia [MWs/MVA]
        hg,     ///< \f$H_{\mathrm{g}}\f$ Generator inertia [MWs/MVA]
        dshaft, ///< \f$D_{\mathrm{shaft}}\f$ Damping coefficient [pu]
        kshaft, ///< \f$K_{\mathrm{shaft}}\f$ Stiffness constant [pu]
        wo,     ///< \f$W_{\mathrm{o}}\f$ Initial shaft speed [pu]
      };

      /// Bus keys for the WTGTA model; deferred until port integration.
      enum class WtgtaBuses : size_t
      {
        SIZE
      };

      /// Signal input keys for the WTGTA model; deferred until port integration.
      enum class WtgtaSignalInputs : size_t
      {
        SIZE
      };

      /// Signal output keys for the WTGTA model; deferred until port integration.
      enum class WtgtaSignalOutputs : size_t
      {
        SIZE
      };

      /// Monitorable variables for the WTGTA model; deferred until implementation.
      enum class WtgtaMonitorableVariables
      {
        NONE
      };

      /**
       * @brief Model data for WTGTA.
       *
       * @tparam real_type Real parameter value type.
       * @tparam index_type Integer index type.
       */
      template <typename real_type, typename index_type>
      struct WtgtaData : public ComponentData<real_type,
                                              index_type,
                                              WtgtaParameters,
                                              WtgtaBuses,
                                              WtgtaSignalInputs,
                                              WtgtaSignalOutputs,
                                              WtgtaMonitorableVariables>
      {
        WtgtaData() = default;

        using Parameters           = WtgtaParameters;
        using Buses                = WtgtaBuses;
        using SignalInputs         = WtgtaSignalInputs;
        using SignalOutputs        = WtgtaSignalOutputs;
        using MonitorableVariables = WtgtaMonitorableVariables;
      };
    } // namespace Wind
  } // namespace PhasorDynamics
} // namespace GridKit
