/**
 * @file WtgaaData.hpp
 * @brief Modeling data for the WTGAA model.
 *
 * Generated by GridKit/Model/PhasorDynamics/data/models.py
 */

#pragma once

#include <cstddef>

#include <GridKit/Model/PhasorDynamics/ComponentData.hpp>

namespace GridKit
{
  namespace PhasorDynamics
  {
    namespace Wind
    {
      /// Parameter keys for the WTGAA model.
      enum class WtgaaParameters
      {
        Ka,     ///< \f$K_{\mathrm{a}}\f$ Aero-dynamic gain factor [pu]
        theta0, ///< \f$T_{\mathrm{heta0}}\f$ Initial blade pitch angle; 0 at maximum available power, 5-10 if curtailed [deg]
      };

      /// Bus keys for the WTGAA model; deferred until port integration.
      enum class WtgaaBuses : size_t
      {
        SIZE
      };

      /// Signal input keys for the WTGAA model; deferred until port integration.
      enum class WtgaaSignalInputs : size_t
      {
        SIZE
      };

      /// Signal output keys for the WTGAA model; deferred until port integration.
      enum class WtgaaSignalOutputs : size_t
      {
        SIZE
      };

      /// Monitorable variables for the WTGAA model; deferred until implementation.
      enum class WtgaaMonitorableVariables
      {
        NONE
      };

      /**
       * @brief Model data for WTGAA.
       *
       * @tparam real_type Real parameter value type.
       * @tparam index_type Integer index type.
       */
      template <typename real_type, typename index_type>
      struct WtgaaData : public ComponentData<real_type,
                                              index_type,
                                              WtgaaParameters,
                                              WtgaaBuses,
                                              WtgaaSignalInputs,
                                              WtgaaSignalOutputs,
                                              WtgaaMonitorableVariables>
      {
        WtgaaData() = default;

        using Parameters           = WtgaaParameters;
        using Buses                = WtgaaBuses;
        using SignalInputs         = WtgaaSignalInputs;
        using SignalOutputs        = WtgaaSignalOutputs;
        using MonitorableVariables = WtgaaMonitorableVariables;
      };
    } // namespace Wind
  } // namespace PhasorDynamics
} // namespace GridKit
