/**
 * @file Tgov1dData.hpp
 * @brief Modeling data for the TGOV1D model.
 *
 * Generated by GridKit/Model/PhasorDynamics/data/models.py
 */

#pragma once

#include <cstddef>

#include <GridKit/Model/PhasorDynamics/ComponentData.hpp>

namespace GridKit
{
  namespace PhasorDynamics
  {
    namespace Governor
    {
      /// Parameter keys for the TGOV1D model.
      enum class Tgov1dParameters
      {
        R,     ///< \f$R\f$ Permanent droop [pu]
        T1,    ///< \f$T_{1}\f$ Steam bowl time constant [s]
        Vmax,  ///< \f$V_{\mathrm{max}}\f$ Maximum valve position limit
        Vmin,  ///< \f$V_{\mathrm{min}}\f$ Minimum valve position limit
        T2,    ///< \f$T_{2}\f$ Numerator time constant of T2, T3 block [s]
        T3,    ///< \f$T_{3}\f$ Reheater time constant [s]
        Dt,    ///< \f$D_{\mathrm{t}}\f$ Turbine damping coefficient [pu]
        dbH,   ///< \f$d_{\mathrm{bH}}\f$ Deadband High [pu]
        dbL,   ///< \f$d_{\mathrm{bL}}\f$ Deadband Low [pu]
        Trate, ///< \f$T_{\mathrm{rate}}\f$ Turbine rating [MW]
      };

      /// Bus keys for the TGOV1D model; deferred until port integration.
      enum class Tgov1dBuses : size_t
      {
        SIZE
      };

      /// Signal input keys for the TGOV1D model; deferred until port integration.
      enum class Tgov1dSignalInputs : size_t
      {
        SIZE
      };

      /// Signal output keys for the TGOV1D model; deferred until port integration.
      enum class Tgov1dSignalOutputs : size_t
      {
        SIZE
      };

      /// Monitorable variables for the TGOV1D model; deferred until implementation.
      enum class Tgov1dMonitorableVariables
      {
        NONE
      };

      /**
       * @brief Model data for TGOV1D.
       *
       * @tparam real_type Real parameter value type.
       * @tparam index_type Integer index type.
       */
      template <typename real_type, typename index_type>
      struct Tgov1dData : public ComponentData<real_type,
                                               index_type,
                                               Tgov1dParameters,
                                               Tgov1dBuses,
                                               Tgov1dSignalInputs,
                                               Tgov1dSignalOutputs,
                                               Tgov1dMonitorableVariables>
      {
        Tgov1dData() = default;

        using Parameters           = Tgov1dParameters;
        using Buses                = Tgov1dBuses;
        using SignalInputs         = Tgov1dSignalInputs;
        using SignalOutputs        = Tgov1dSignalOutputs;
        using MonitorableVariables = Tgov1dMonitorableVariables;
      };
    } // namespace Governor
  } // namespace PhasorDynamics
} // namespace GridKit
