/**
 * @file Regfmb1Data.hpp
 * @brief Modeling data for the REGFMB1 model.
 *
 * Generated by GridKit/Model/PhasorDynamics/data/models.py
 */

#pragma once

#include <cstddef>

#include <GridKit/Model/PhasorDynamics/ComponentData.hpp>

namespace GridKit
{
  namespace PhasorDynamics
  {
    namespace Converter
    {
      /// Parameter keys for the REGFMB1 model.
      enum class Regfmb1Parameters
      {
        wFlag,    ///< \f$\omega_{\mathrm{Flag}}\f$ A flag to select whether to use the measured frequency from PLL as the input for the P-f droop
        VdrpFlag, ///< \f$V_{\mathrm{drpFlag}}\f$ A flag to select whether to use Q or Iq as the input of the Q-V droop control
        QVFlag,   ///< \f$Q_{\mathrm{VFlag}}\f$ A flag to determine whether Qref or Vref should be used to interact with the plant controller
        PQFlag,   ///< \f$P_{\mathrm{QFlag}}\f$ A flag to determine whether P priority (1) or Q priority (0) should be selected
        FFlag,    ///< \f$F_{\mathrm{Flag}}\f$ A flag to determine whether the power-frequency droop is enabled (1) or disabled (0)
        ESFlag,   ///< \f$E_{\mathrm{SFlag}}\f$ A flag to determine if the model represents a battery source (1) or a non-battery source (0)
        Re,       ///< \f$R_{\mathrm{e}}\f$ Inverter coupling resistance (0 pu <= Re <= XL/4) [pu]
        XL,       ///< \f$X_{\mathrm{L}}\f$ Inverter coupling reactance (0.04 pu <= XL <= 0.4 pu) [pu]
        mq,       ///< \f$m_{\mathrm{q}}\f$ Q-V droop gain; when VdrpFlag=1 this represents a per unit virtual impedance [pu]
        kpv,      ///< \f$k_{\mathrm{pv}}\f$ Proportional gain of the voltage controller [pu]
        kiv,      ///< \f$k_{\mathrm{iv}}\f$ Integral gain of the voltage controller [pu/s]
        mp,       ///< \f$m_{\mathrm{p}}\f$ P-f droop gain [pu]
        dwmax,    ///< \f$\Delta\omega_{\mathrm{max}}\f$ Upper limit of the VSM integrator output [pu]
        dwmin,    ///< \f$\Delta\omega_{\mathrm{min}}\f$ Lower limit of the VSM integrator output [pu]
        kpPLL,    ///< \f$k_{\mathrm{pPLL}}\f$ Proportional gain of PLL [pu]
        kiPLL,    ///< \f$k_{\mathrm{iPLL}}\f$ Integral gain of PLL [pu/s]
        dwPLLmax, ///< \f$\Delta\omega_{\mathrm{PLLmax}}\f$ Upper limit of the PLL output [pu]
        dwPLLmin, ///< \f$\Delta\omega_{\mathrm{PLLmin}}\f$ Lower limit of the PLL output [pu]
        Tp,       ///< \f$T_{\mathrm{p}}\f$ Time constant of the low-pass filter in the VSM control block (Tp >= 0) [s]
        H,        ///< \f$H\f$ Inertia time constant [s]
        D1,       ///< \f$D_{1}\f$ Damping [pu]
        D2,       ///< \f$D_{2}\f$ Transient damping [pu]
        wD,       ///< \f$\omega_{\mathrm{D}}\f$ Angular frequency of the washout block [pu]
        ImaxSS,   ///< \f$I_{\mathrm{maxSS}}\f$ Steady-state current limit; ImaxSS <= 0 is treated as 1/XL, and ImaxSS <= ImaxF [pu]
        kf,       ///< \f$k_{\mathrm{f}}\f$ Factor determining Iqmax (PQFlag=0) or Idmax (PQFlag=1); if 0 the software resets it to 1 with a warning
        kI,       ///< \f$k_{\mathrm{I}}\f$ Integral gain for the active current limiting loop [pu/s]
        ImaxF,    ///< \f$I_{\mathrm{maxF}}\f$ Transient current limit [pu]
        TPf,      ///< \f$T_{\mathrm{Pf}}\f$ Time constant of the low-pass filter for active power measurement [s]
        TQf,      ///< \f$T_{\mathrm{Qf}}\f$ Time constant of the low-pass filter for reactive power measurement [s]
        TVf,      ///< \f$T_{\mathrm{Vf}}\f$ Time constant of the low-pass filter for voltage measurement [s]
        TIf,      ///< \f$T_{\mathrm{If}}\f$ Time constant of the low-pass filter for current measurement [s]
        Ke,       ///< \f$K_{\mathrm{e}}\f$ Scalar on Idmax for negative active steady-state current limitation (0 <= Ke <= 1)
        w0,       ///< \f$\omega_{0}\f$ Rated angular frequency; usually set in the solution environment rather than as a model input [rad/s]
      };

      /// Bus keys for the REGFMB1 model; deferred until port integration.
      enum class Regfmb1Buses : size_t
      {
        SIZE
      };

      /// Signal input keys for the REGFMB1 model; deferred until port integration.
      enum class Regfmb1SignalInputs : size_t
      {
        SIZE
      };

      /// Signal output keys for the REGFMB1 model; deferred until port integration.
      enum class Regfmb1SignalOutputs : size_t
      {
        SIZE
      };

      /// Monitorable variables for the REGFMB1 model; deferred until implementation.
      enum class Regfmb1MonitorableVariables
      {
        NONE
      };

      /**
       * @brief Model data for REGFMB1.
       *
       * @tparam real_type Real parameter value type.
       * @tparam index_type Integer index type.
       */
      template <typename real_type, typename index_type>
      struct Regfmb1Data : public ComponentData<real_type,
                                                index_type,
                                                Regfmb1Parameters,
                                                Regfmb1Buses,
                                                Regfmb1SignalInputs,
                                                Regfmb1SignalOutputs,
                                                Regfmb1MonitorableVariables>
      {
        Regfmb1Data() = default;

        using Parameters           = Regfmb1Parameters;
        using Buses                = Regfmb1Buses;
        using SignalInputs         = Regfmb1SignalInputs;
        using SignalOutputs        = Regfmb1SignalOutputs;
        using MonitorableVariables = Regfmb1MonitorableVariables;
      };
    } // namespace Converter
  } // namespace PhasorDynamics
} // namespace GridKit
