/**
 * @file WtgtbData.hpp
 * @brief Modeling data for the WTGTB model.
 *
 * Generated by GridKit/Model/PhasorDynamics/data/models.py
 */

#pragma once

#include <cstddef>

#include <GridKit/Model/PhasorDynamics/ComponentData.hpp>

namespace GridKit
{
  namespace PhasorDynamics
  {
    namespace Wind
    {
      /// Parameter keys for the WTGTB model.
      enum class WtgtbParameters
      {
        ht,     ///< \f$H_{\mathrm{t}}\f$ Turbine inertia [MWs/MVA]
        hg,     ///< \f$H_{\mathrm{g}}\f$ Generator inertia [MWs/MVA]
        dshaft, ///< \f$D_{\mathrm{shaft}}\f$ Damping coefficient [pu]
        kshaft, ///< \f$K_{\mathrm{shaft}}\f$ Stiffness constant [pu]
        wo,     ///< \f$W_{\mathrm{o}}\f$ Initial shaft speed [pu]
        Tp,     ///< \f$T_{\mathrm{p}}\f$ Time constant [s]
      };

      /// Bus keys for the WTGTB model; deferred until port integration.
      enum class WtgtbBuses : size_t
      {
        SIZE
      };

      /// Signal input keys for the WTGTB model; deferred until port integration.
      enum class WtgtbSignalInputs : size_t
      {
        SIZE
      };

      /// Signal output keys for the WTGTB model; deferred until port integration.
      enum class WtgtbSignalOutputs : size_t
      {
        SIZE
      };

      /// Monitorable variables for the WTGTB model; deferred until implementation.
      enum class WtgtbMonitorableVariables
      {
        NONE
      };

      /**
       * @brief Model data for WTGTB.
       *
       * @tparam real_type Real parameter value type.
       * @tparam index_type Integer index type.
       */
      template <typename real_type, typename index_type>
      struct WtgtbData : public ComponentData<real_type,
                                              index_type,
                                              WtgtbParameters,
                                              WtgtbBuses,
                                              WtgtbSignalInputs,
                                              WtgtbSignalOutputs,
                                              WtgtbMonitorableVariables>
      {
        WtgtbData() = default;

        using Parameters           = WtgtbParameters;
        using Buses                = WtgtbBuses;
        using SignalInputs         = WtgtbSignalInputs;
        using SignalOutputs        = WtgtbSignalOutputs;
        using MonitorableVariables = WtgtbMonitorableVariables;
      };
    } // namespace Wind
  } // namespace PhasorDynamics
} // namespace GridKit
